language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"
script:
  - npm run build
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key ian@nextlevel.hldns.ru pwd

before_install:
- openssl aes-256-cbc -K $encrypted_7bd55255072d_key -iv $encrypted_7bd55255072d_iv
  -in id_rsa_dep.enc -out ./deploy_key -d
