language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
script:
- npm run build
- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa_dep
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./id_rsa_dep
- ssh -i ./id_rsa_dep ian@nextlevel.hldns.ru pwd
before_install:
- openssl aes-256-cbc -K $encrypted_7bd55255072d_key -iv $encrypted_7bd55255072d_iv -in id_rsa_dep.enc -out ./id_rsa_dep -d
