language: node_js
node_js:
  - 10
cache:
  directories:
    - "node_modules"
script:
  - npm run build
  - eval "$(ssh-agent -s)"
  - chmod 600 ../../../../../../.ssh/id_rsa_dep
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ../../../../../../.ssh/id_rsa_dep
  - ssh -i ../../../../../../.ssh/id_rsa_dep ian@nextlevel.hldns.ru pwd

before_install:
- openssl aes-256-cbc -K $encrypted_7bd55255072d_key -iv $encrypted_7bd55255072d_iv
  -in id_rsa_dep.enc -out ../../../../../../.ssh/id_rsa_dep -d

